-- Versioned production seed for the Vibe & Events MVP.
-- Idempotent by design; see resort_events_unique_seed_idx.

with event_seed (
  resort_slugs,
  name,
  event_type,
  music_genres,
  vibe_tags,
  start_date,
  end_date,
  recurring_month,
  location_name,
  altitude_m,
  ticket_required,
  ticket_price_from,
  official_url,
  short_description,
  best_for,
  not_ideal_for,
  data_quality,
  last_checked_at
) as (
  values
    (
      array['solden'],
      'Electric Mountain Festival',
      'festival',
      array['EDM', 'Electronic', 'House'],
      array['party', 'young_crowd', 'electronic', 'big_stage', 'mountain_stage'],
      '2026-04-14'::date,
      '2026-04-18'::date,
      4::smallint,
      'Sölden / Giggijoch',
      2284,
      true,
      null::numeric,
      'https://www.soelden.com/en/events-leisure-tips/events/electric-mountain-festival/faqs',
      'Elektronisches Musikfestival im Skigebiet Sölden mit Bergbühnen und Club-Vibe.',
      'Gruppen, EDM-Fans und Reisende, die bewusst ein Event in den Skitrip einbauen.',
      'Gäste, die in der Eventwoche Ruhe, günstige Unterkünfte oder leere Orte suchen.',
      'outdated',
      '2026-05-07'::timestamptz
    ),
    (
      array['alpe-d-huez-grand-domaine', 'alpe-d-huez'],
      'Tomorrowland Winter',
      'festival',
      array['EDM', 'Electronic', 'House', 'Techno'],
      array['party', 'young_crowd', 'premium', 'electronic', 'big_stage', 'mountain_stage'],
      null::date,
      null::date,
      3::smallint,
      'Alpe d''Huez',
      1860,
      true,
      null::numeric,
      'https://winter.tomorrowland.com/en/welcome/',
      'Großes Winter-Festival von Tomorrowland in Alpe d''Huez mit elektronischem Schwerpunkt.',
      'Internationale Gruppen, EDM-Fans und Gäste mit Festival-Fokus.',
      'Ruhesuchende und sehr budgetorientierte Trips während der Festivalwoche.',
      'estimated',
      '2026-05-07'::timestamptz
    ),
    (
      array['silvretta-arena-ischgl-samnaun', 'ischgl'],
      'Top of the Mountain Closing Concert',
      'concert',
      array['Pop', 'Mainstream', 'Live Music'],
      array['party', 'premium', 'live_music', 'big_stage', 'mountain_stage'],
      '2027-05-01'::date,
      '2027-05-01'::date,
      5::smallint,
      'Ischgl / Idalp',
      2320,
      true,
      null::numeric,
      'https://www.ischgl.com/en/events-experiences/topevents',
      'Saisonabschluss-Konzert im Skigebiet Ischgl mit großer Open-Air-Bühne.',
      'Gruppen, Konzertfans und Reisende, die Skiurlaub mit einem Live-Event verbinden.',
      'Gäste, die am Saisonfinale niedrige Preise und wenig Andrang erwarten.',
      'official',
      '2026-05-07'::timestamptz
    ),
    (
      array['avoriaz'],
      'Snowboxx',
      'festival',
      array['Electronic', 'House', 'Drum and Bass', 'Party'],
      array['party', 'young_crowd', 'student_friendly', 'electronic', 'big_stage'],
      null::date,
      null::date,
      3::smallint,
      'Avoriaz',
      1800,
      true,
      null::numeric,
      'https://www.snowboxx.com/',
      'Festivalwoche in Avoriaz mit elektronischer Musik, Partys und Skiurlaub in einem autofreien Resort.',
      'Freundesgruppen, Studenten und junge Reisende mit Party-Fokus.',
      'Ruhesuchende, Familien mit frühem Tagesrhythmus und sehr flexible Budget-Trips.',
      'estimated',
      '2026-05-07'::timestamptz
    ),
    (
      array['les-deux-alpes'],
      'Rise Festival',
      'festival',
      array['Electronic', 'House', 'Techno', 'Party'],
      array['party', 'young_crowd', 'student_friendly', 'electronic', 'mountain_stage'],
      '2026-12-05'::date,
      '2026-12-12'::date,
      12::smallint,
      'Les Deux Alpes',
      1650,
      true,
      null::numeric,
      'https://www.rise-festival.com/homepage',
      'Winter-Festival in Les Deux Alpes mit elektronischer Musik, Clubnächten und Bergprogramm.',
      'Freundesgruppen, Studenten und Reisende, die Saisonstart und Festival verbinden.',
      'Trips mit starkem Ruhe- oder Familienfokus während der Festivalwoche.',
      'official',
      '2026-05-07'::timestamptz
    ),
    (
      array['avoriaz', 'les-gets-morzine', 'champery-les-crosets-champoussin-morgins', 'espace-liberte'],
      'Rock the Pistes',
      'festival',
      array['Rock', 'Pop', 'Indie', 'Live Music'],
      array['live_music', 'mountain_stage', 'young_crowd', 'big_stage'],
      '2026-03-15'::date,
      '2026-03-21'::date,
      3::smallint,
      'Portes du Soleil',
      null::integer,
      false,
      null::numeric,
      'https://www.rockthepistes.com/',
      'Grenzüberschreitendes Musikfestival in Portes du Soleil mit Konzerten auf und neben der Piste.',
      'Live-Musik-Fans, Gruppen und Reisende, die ein Festival ohne reinen EDM-Fokus suchen.',
      'Reisende, die sehr ruhige Pistentage und planbare Ortswechsel priorisieren.',
      'outdated',
      '2026-05-07'::timestamptz
    ),
    (
      array['skicircus-saalbach-hinterglemm-leogang-fieberbrunn', 'saalbach-hinterglemm'],
      'Rave on Snow',
      'festival',
      array['Electronic', 'Techno', 'House'],
      array['party', 'young_crowd', 'electronic', 'live_music'],
      '2026-12-10'::date,
      '2026-12-13'::date,
      12::smallint,
      'Saalbach-Hinterglemm',
      null::integer,
      true,
      null::numeric,
      'https://raveonsnow.com/en',
      'Elektronisches Winter-Event in Saalbach-Hinterglemm mit Techno- und House-Schwerpunkt.',
      'Techno-/House-Fans und Gruppen, die ein kompaktes Event-Wochenende suchen.',
      'Ruhige Advents-Wochenenden und Gäste mit sehr niedrigem Party-Interesse.',
      'official',
      '2026-05-07'::timestamptz
    ),
    (
      array['skicircus-saalbach-hinterglemm-leogang-fieberbrunn', 'saalbach-hinterglemm'],
      'Bergfestival',
      'festival',
      array['Pop', 'Rock', 'Indie', 'Live Music'],
      array['live_music', 'young_crowd', 'party', 'mountain_stage'],
      '2026-12-04'::date,
      '2026-12-06'::date,
      12::smallint,
      'Saalbach-Hinterglemm',
      null::integer,
      true,
      null::numeric,
      'https://www.berg-festival.com/',
      'Mehrtaegiges Musikfestival in Saalbach-Hinterglemm mit Pop-, Rock- und Live-Musik-Fokus.',
      'Gruppen, Live-Musik-Fans und Reisende, die ein Eventwochenende im Schnee suchen.',
      'Gäste, die Anfang Dezember bewusst sehr ruhige Orte bevorzugen.',
      'official',
      '2026-05-07'::timestamptz
    ),
    (
      array['mayrhofen-hippach', 'mayrhofen'],
      'Snowbombing',
      'festival',
      array['Electronic', 'House', 'Techno', 'Hip-Hop'],
      array['party', 'young_crowd', 'electronic', 'big_stage', 'live_music'],
      null::date,
      null::date,
      4::smallint,
      'Mayrhofen',
      633,
      true,
      null::numeric,
      'https://snowbombing.com/',
      'Bekanntes Musik- und Ski-Festival in Mayrhofen mit Clubnächten, Live-Acts und Bergprogramm.',
      'Internationale Gruppen und Reisende, die Musik, Nightlife und Skiurlaub kombinieren.',
      'Sehr ruhige Trips, Familienfokus oder knappe Budgets in der Festivalwoche.',
      'estimated',
      '2026-05-07'::timestamptz
    ),
    (
      array['val-thorens-orelle', 'val-thorens'],
      'Dutchweek Val Thorens',
      'local_event',
      array['Après-Ski', 'Pop', 'Party'],
      array['party', 'young_crowd', 'apres_ski', 'student_friendly'],
      '2026-04-25'::date,
      '2026-05-02'::date,
      4::smallint,
      'Val Thorens',
      2300,
      false,
      null::numeric,
      'https://www.valthorens.com/en/agenda-manifestation/dutch-week/occ/6/',
      'Saisonales Eventformat in Val Thorens mit Après-Ski, Gruppenstimmung und End-of-season-Vibe.',
      'Freundesgruppen, Après-Ski-Fans und Reisende, die eine lebhafte Woche suchen.',
      'Ruhesuchende und Gäste, die volle Terrassen und höhere Nachfrage vermeiden möchten.',
      'outdated',
      '2026-05-07'::timestamptz
    ),
    (
      array['zermatt-breuil-cervinia-breuil-cervinia-ski-paradise', 'zermatt'],
      'Zermatt Unplugged',
      'festival',
      array['Pop', 'Rock', 'Indie', 'Live Music'],
      array['premium', 'live_music', 'mountain_stage'],
      '2026-04-07'::date,
      '2026-04-11'::date,
      4::smallint,
      'Zermatt',
      1608,
      true,
      null::numeric,
      'https://zermatt-unplugged.ch/',
      'Akustik- und Live-Musik-Festival in Zermatt mit Konzerten im Ort und alpinem Premium-Kontext.',
      'Paare, Freundesgruppen und Live-Musik-Fans mit Premium- und Genussfokus.',
      'Sehr budgetorientierte Trips oder Gäste, die große Eventnachfrage vermeiden wollen.',
      'outdated',
      '2026-05-07'::timestamptz
    )
),
matched_events as (
  select
    resort.id as resort_id,
    event_seed.*
  from event_seed
  join lateral (
    select id
    from public.resorts
    where slug = any(event_seed.resort_slugs)
    order by array_position(event_seed.resort_slugs, slug) nulls last
    limit 1
  ) resort on true
)
insert into public.resort_events (
  resort_id,
  name,
  event_type,
  music_genres,
  vibe_tags,
  start_date,
  end_date,
  recurring_month,
  location_name,
  altitude_m,
  ticket_required,
  ticket_price_from,
  official_url,
  short_description,
  best_for,
  not_ideal_for,
  data_quality,
  last_checked_at
)
select
  resort_id,
  name,
  event_type,
  music_genres,
  vibe_tags,
  start_date,
  end_date,
  recurring_month,
  location_name,
  altitude_m,
  ticket_required,
  ticket_price_from,
  official_url,
  short_description,
  best_for,
  not_ideal_for,
  data_quality,
  last_checked_at
from matched_events
on conflict do nothing;
